# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 07:00
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20160610_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
