# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20160610_0713'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='providers.Provider'),
            preserve_default=False,
        ),
    ]
